--- 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  name: k8s-jobs-poc-test-1
spec: 
  entrypoint: spring-boot-app
  templates: 
    - name: spring-boot-app
      resource: 
        action: apply
        manifest:
          apiVersion: apps/v1
          kind: Job
          metadata: 
            labels: 
              app: spring-boot-app
            name: spring-boot-app
          spec: 
            replicas: 1
            selector: 
              matchLabels: 
                app: spring-boot-app
            template: 
              metadata: 
                labels: 
                  app: spring-boot-app
              spec: 
                containers: 
                  - image: gazgeek/springboot-helloworld
                    imagePullPolicy: always
                    name: spring-boot-app
